### ISSUE TITLE
[FEAT]: Rename to .github?

### ISSUE THREAD

**Issue by engeir** [uit-cosmo/user-guide#19]
There is the possibility of having a public README for the organization that shows up on the profile, [documented here](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile). Since we already have a repo with such a README, I think just renaming the repo from "user-guide" to ".github" should have the same effect, as well as placing the README file in a profile directory. Would look like [this](https://github.com/github).

**Comment by gregordecristoforo** [comment]
That's a really good idea!
