### ISSUE TITLE
Equations not visible in dark mode

### ISSUE THREAD

**Issue by sajidah-ahmed** [uit-cosmo/user-guide#7]
Perhaps put a white background behind all equations.

**Comment by engeir** [comment]
This works:

<img src="https://render.githubusercontent.com/render/math?math={\L = -\sum_{j}[T_{j}\ln(O_{j})] %2B \frac{\lambda W_{ij}^{2}}{2} \rightarrow \text{one-hot} \rightarrow -\ln(O_{c}) %2B \frac{\lambda W_{ij}^{2}}{2}}#gh-light-mode-only">
<img src="https://render.githubusercontent.com/render/math?math={\color{white}\L = -\sum_{j}[T_{j}\ln(O_{j})] %2B \frac{\lambda W_{ij}^{2}}{2} \rightarrow \text{one-hot} \rightarrow -\ln(O_{c}) %2B \frac{\lambda W_{ij}^{2}}{2}}#gh-dark-mode-only">

is generated from

```html
<img src="https://render.githubusercontent.com/render/math?math={\L = -\sum_{j}[T_{j}\ln(O_{j})] %2B \frac{\lambda W_{ij}^{2}}{2} \rightarrow \text{one-hot} \rightarrow -\ln(O_{c}) %2B \frac{\lambda W_{ij}^{2}}{2}}#gh-light-mode-only">
<img src="https://render.githubusercontent.com/render/math?math={\color{white}\L = -\sum_{j}[T_{j}\ln(O_{j})] %2B \frac{\lambda W_{ij}^{2}}{2} \rightarrow \text{one-hot} \rightarrow -\ln(O_{c}) %2B \frac{\lambda W_{ij}^{2}}{2}}#gh-dark-mode-only">
```

See [this answer](https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b?permalink_comment_id=4073555#gistcomment-4073555)

Note that `+` does not always render well (commented on [here](https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b?permalink_comment_id=4064378#gistcomment-4064378)), so `%2B` is used instead.

**Comment by engeir** [comment]
Never mind: [GitHub now support math](https://github.blog/2022-05-19-math-support-in-markdown/)

Inline $mat_h$, and

$$
blo_ck
$$

math.

@gregordecristoforo
